### ISSUE TITLE
Importing AttributeError: 'bool' object has no attribute 'output'

### ISSUE THREAD

**Issue by Davide-sd** [gutow/Algebra_with_Sympy#30]
I have a module, named `control_utils.py`, which has the following import and configuration:

```py
from algebra_with_sympy import Eqn, solve as esolve, algwsym_config
algwsym_config.output.label = False
algwsym_config.output.solve_to_list = True

__all__ = ["my_func_name_1", ...]
```

The reason I put the configuration into my module is that I find it boring typing them on every new Jupyter notebooks. So it's there, it gets executed once when the module is loaded, which is done with  `from control_utils import *`.

Everything worked fine with `algebra_with_sympy` version `0.12.0`. However, with the latest version I get this error when trying to display an equation on the notebook:

```py
from sympy import *
from control_utils import *
init_printing()
xi, wn = symbols("xi omega_n", real=True, positive=True)
Tp, Ts = symbols("T_p, T_s", real=True, positive=True)
e1 = Eqn(Tp, pi / (wn*sqrt(1 - xi**2)))
e2 = Eqn(Ts, 4 / (wn*xi))
e1
```
```text
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File ~/Documents/Development/envs/control/lib/python3.10/site-packages/IPython/core/formatters.py:340, in BaseFormatter.__call__(self, obj)
    338     pass
    339 else:
--> 340     return printer(obj)
    341 # Finally look for special method names
    342 method = get_real_method(obj, self.print_method)

File ~/Documents/Development/Algebra_with_Sympy/algebra_with_sympy/algebraic_equation.py:413, in __latex_override__(expr, *arg)
    411 if isinstance(expr, Equation):
    412     namestr = expr._get_eqn_name()
--> 413 if namestr != '' and algwsym_config.output.label:
    414     tempstr += '\\,\\,\\,\\,\\,\\,\\,\\,\\,\\,'
    415     tempstr += '(\\text{' + namestr + '})'

AttributeError: 'bool' object has no attribute 'output'
```

Importing `algwsym_config` into the notebook makes everything works fine again:

```py
from sympy import *
from control_utils import *
from algebra_with_sympy import algwsym_config
init_printing()
xi, wn = symbols("xi omega_n", real=True, positive=True)
Tp, Ts = symbols("T_p, T_s", real=True, positive=True)
e1 = Eqn(Tp, pi / (wn*sqrt(1 - xi**2)))
e2 = Eqn(Ts, 4 / (wn*xi))
e1
```
![image](https://github.com/gutow/Algebra_with_Sympy/assets/9921777/a08a498e-8188-45e3-bbfe-444fce235f82)

Would it be possible to replicate the behavior of the previous version?

**Comment by Davide-sd** [comment]
Ohhh well, I just realized that I can simply add `"algwsym_config"` to `_all_`, and everything works as intended again. I think this issue can be closed...

**Comment by gutow** [comment]
> Ohhh well, I just realized that I can simply add `"algwsym_config"` to `_all_`, and everything works as intended again. I think this issue can be closed...

Closing...
